#Get the REST Client extension by Huachao Mao and click Send Request above each endpoint 
#on this file if you would like to test these endpoints in vscode 👍

GET http://localhost:3000/hello
###

#__________________________________GET___________________________________________________________________

# GET all entity items for the authenticated user. 
GET http://localhost:3000/api/v1/notes
###
GET http://localhost:3000/api/v1/todo-items
###
GET http://localhost:3000/api/v1/time-tracker-items
###
GET http://localhost:3000/api/v1/appointments
###
#_______________________________________________________________________________________________________


#__________________________________PATCH is_deleted_____________________________________________________
# "delete" a :table item at specified :id...  /remove/:table/:id
PATCH http://localhost:3000/api/v1/remove/time_tracker_items/2
###
PATCH http://localhost:3000/api/v1/remove/appointments/2
###
#_______________________________________________________________________________________________________


#__________________________________PATCH updates________________________________________________________

#the endpoint below toggles between true and false for is_completed
PATCH http://localhost:3000/api/v1/update/todo-item-completion/2   
###

PATCH http://localhost:3000/api/v1/update/time-tracker-unit/6
Content-Type: application/json

{
  "time_unit": 2
}

###

#update length of time tracker item
PATCH http://localhost:3000/api/v1/update/time-tracker-length/6
Content-Type: application/json

{
  "length": 200
}

###
#_______________________________________________________________________________________________________


#__________________________________POST_________________________________________________________________
# Create Appointment
POST http://localhost:3000/api/v1/create/appointments
Content-Type: application/json

{
  "title": "Team Meeting",
  "description": "Discuss project updates and upcoming tasks.",
  "start_time": "2024-06-15T10:00:00Z",
  "length": 60
}

###

# Create Note
POST http://localhost:3000/api/v1/create/notes
Content-Type: application/json

{
  "title": "Project Notes",
  "content": "Discussed progress on current tasks."
}

###

# Create Time Tracker Item
POST http://localhost:3000/api/v1/create/time-tracker-items
Content-Type: application/json

{
  "description": "Work on documentation",
  "length": 120,
  "time_unit": 1
}

###

# Create Todo Item
POST http://localhost:3000/api/v1/create/todo-items
Content-Type: application/json

{
  "item": "Finish report"
}
###

# Add user
POST http://localhost:3000/api/v1/create/user
Content-Type: application/json

#_______________________________________________________________________________________________________