#Get the REST Client extension by Huachao Mao and click Send Request above each endpoint 
#on this file if you would like to test these endpoints in vscode 👍

GET https://localhost:8080/hello
###

#__________________________________GET___________________________________________________________________

# GET all entity items for the authenticated user. 
GET https://localhost:8080/api/v1/notes 
###
GET https://localhost:8080/api/v1/todo-items
###
GET https://localhost:8080/api/v1/time-tracker-items
###
GET https://localhost:8080/api/v1/appointments
###
#_______________________________________________________________________________________________________


#__________________________________PATCH is_deleted_____________________________________________________
# "delete" a :table item at specified :id...  /remove/:table/:id  The table name must match the database
PATCH https://localhost:8080/api/v1/remove/TimeTrackerItems/1
###
PATCH https://localhost:8080/api/v1/remove/Appointments/1
###
#_______________________________________________________________________________________________________


#__________________________________PATCH updates________________________________________________________

#the endpoint below toggles between true and false for is_completed
PATCH https://localhost:8080/api/v1/update/todo-item-completion/1   
###

PATCH https://localhost:8080/api/v1/update/time-tracker-unit/1
Content-Type: application/json

{
  "time_unit": 2
}

###

#update length of time tracker item
PATCH https://localhost:8080/api/v1/update/time-tracker-length/1
Content-Type: application/json

{
  "length": 200
}

###
#_______________________________________________________________________________________________________


#__________________________________POST_________________________________________________________________
# Create Appointment
POST https://localhost:8080/api/v1/create/appointments
Content-Type: application/json

{
  "title": "Team Meeting2",
  "description": "Discuss project updates and upcoming tasks.",
  "start_time": "2024-06-15T10:00:00Z",
  "length": 6
}

###

# Create Note
POST https://localhost:8080/api/v1/create/notes
Content-Type: application/json

{
  "title": "Project Notes2ss",
  "content": "Discussed progress many things"
}

###

# Create Time Tracker Item
POST https://localhost:8080/api/v1/create/time-tracker-items
Content-Type: application/json

{
  "description": "Work on documentation",
  "length": 120,
  "time_unit": 1
}

###

# Create Todo Item
POST https://localhost:8080/api/v1/create/todo-items
Content-Type: application/json

{
  "item": "Finish report"
}
###

# Add user
POST https://localhost:8080/api/v1/create/user
Content-Type: application/json

#_______________________________________________________________________________________________________