name: Deploy Backend

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-my-planner-build
          aws-region: eu-west-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Package artifact
        run: zip -r ../dist.zip .
        working-directory: backend

      - name: Upload artifact to S3
        run: aws s3 cp dist.zip s3://${{ secrets.BACKEND_BUCKET_NAME }}/application-${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-dev-do-list-build
          aws-region: eu-west-1

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.BACKEND_BUCKET_NAME }}",S3Key="application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.APP_NAME }} --environment-name ${{ secrets.ENV_NAME }} --version-label ${{ github.run_id }}